### ISSUE TITLE
Proxy implementation doesn't working with Torguard

### ISSUE THREAD

**Issue by github59173** [MehdiRtal/MicrosoftRewardsFarmerV2#14]
I've been trying to run the script using an HTTPS proxy provided by TorGuard (https://torguard.net/network/ssl/), but I am consistently encountering an error when the script tries to navigate to "https://rewards.bing.com/". The error message is "Connection terminated unexpectedly".

I modified the script to output a debug log and temporarily removed the abc function as discussed in the previous issue report.
```
2023-07-02 01:13:54,386 - INFO - Starting script with 1 workers
2023-07-02 01:13:54,387 - INFO - Starting farm process for account: ██████████
2023-07-02 01:13:54,388 - DEBUG - Using selector: EpollSelector
2023-07-02 01:13:56,495 - ERROR - Failed to perform operation
Traceback (most recent call last):
  File "/home/user/MicrosoftRewardsFarmerV2-main(abc_quiz_removed)/./main_with_logging.py", line 27, in farm
    rewards.login(account["username"], account["password"])
  File "/home/user/MicrosoftRewardsFarmerV2-main(abc_quiz_removed)/rewards.py", line 36, in login
    self.page.goto("https://rewards.bing.com/")
  File "/home/user/.local/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 9293, in goto
    self._sync(
  File "/home/user/.local/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/playwright/_impl/_page.py", line 479, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/user/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Connection terminated unexpectedly
=========================== logs ===========================
navigating to "https://rewards.bing.com/", waiting until "load"
============================================================
```

I've verified that the proxy is working correctly by making requests with the requests library in Python. The issue seems to occur specifically when using the proxy with the Playwright library implementation. I have verified the correct format for the proxy string in the accounts.json file. 

I would appreciate any insights or advice on how to resolve this issue. Please let me know if any additional information is needed.

**Comment by MehdiRtal** [comment]
The script doesn't support SOCKS5 proxies since I've hard-coded "http://" into playwright's proxy string. I can add support for it but you'd have to specify the correct type for every proxy you're adding.

**Comment by MehdiRtal** [comment]
I believe that WebKit doesn't support proxies.

**Comment by MehdiRtal** [comment]
Fixed with the new update.
